In [0]:
import numpy as np

In [0]:
#use numpy.linlg
# A = USV : S is a diagonal matrix which means most of its entries are zeros hence this is a sparse matrix
from numpy.linalg import svd

In [0]:
A = np.array([[4,0],[-3,5]])

U,S,V = svd(A)

In [6]:
print("Left singular \n {}".format(U))

Left singular 
 [[-0.4472136   0.89442719]
 [ 0.89442719  0.4472136 ]]


In [9]:
print("Singular values \n {}".format(np.diag(S)))

Singular values 
 [[6.32455532 0.        ]
 [0.         3.16227766]]


In [8]:
print("Right singular \n {}".format(V))

Right singular 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
# @ is matrix multiplication same as np.matmul

print(U @ np.diag(S) @ V)

[[ 4.00000000e+00 -1.11271234e-15]
 [-3.00000000e+00  5.00000000e+00]]


In [0]:
#Truncated SVD 

In [0]:
from sklearn.decomposition import TruncatedSVD

In [13]:
A = np.array([[-1, 2, 0], [2, 0, -2], [0, -2, 1]])

print("Original Matrix: \n {}".format(A))

Original Matrix: 
 [[-1  2  0]
 [ 2  0 -2]
 [ 0 -2  1]]


In [0]:
svd =  TruncatedSVD(n_components = 2)
A_transf = svd.fit_transform(A)

In [15]:
print("Singular values:")
print(svd.singular_values_)

Singular values:
[3. 3.]


In [16]:
print("Transformed Matrix after reducing to 2 features:")
print(A_transf)

Transformed Matrix after reducing to 2 features:
[[-1.32331203 -1.80245534]
 [-1.6336216   2.30895658]
 [ 2.14012283  0.64797706]]


In [17]:
#faster Truncated svd: randomized svd
from sklearn.utils.extmath import randomized_svd

A = np.array([[-1, 2, 0], [2, 0, -2], [0, -2, 1]])
u, s, vt = randomized_svd(A, n_components = 2)

print("Left Singular Vectors:")
print(u)

print("Singular Values:") 
print(np.diag(s))

print("Right Singular Vectors:") 
print(vt)

Left Singular Vectors:
[[-0.25523068 -0.70029483]
 [ 0.94244607 -0.02615889]
 [-0.21599235  0.71337428]]
Singular Values:
[[3. 0.]
 [0. 3.]]
Right Singular Vectors:
[[ 0.71337428 -0.02615889 -0.70029483]
 [ 0.21599235 -0.94244607  0.25523068]]
